name: QuickBungee
version: 1.1
description: Call Bungeecord's "send" as Spigot Server Command
authors: [Kirastur]
website: https://www.spigotmc.org/resources/quickbungee.93989

api-version: 1.16
load: POSTWORLD
main: de.polarwolf.quickbungee.main.Main

commands:
    quickbungee:
        description: Force a player to bungeejump to another server
        permission: quickbungee.admin
        usage: "Query a list of valid subcommands by using: /quickbungee help"

permissions:
    quickbungee.admin:
        description: Can use the quickbungee command to send players to other servers
        default: OP
